Define `void operator delete[](void *p, std::size_t n)` in new_delete.cpp
This prevents the following warning when compiling with `-Wextra`:

```
[redacted]/pico-sdk/src/rp2_common/pico_standard_link/new_delete.cpp:24:6: error: the program should also define 'void operator delete [](void*, unsigned int)' [-Werror=sized-deallocation]
   24 | void operator delete[](void *p) noexcept { std::free(p); }
      |      ^~~~~~~~
```

This function signature was introduced in C++14. I don't _think_ that should
cause any issues, but I'm not sure.