Fix a bug with the enter/exit critical functions
    The save_and_disable_interrupts function was buggy for two reasons. The first one, it is declared
    as a static inline function; once the function's content is inlined, the compiler is free to
    optimize/reorder the content as it wishes with surrounding instructions. This, combined with the
    fact that the inline assembly "cpsid i" does not contain the trailing `: \"memory\" ` that acts
    like an implicit instruction barrier, this allows the compiler to reorder the instructions
    that disable the interrupts with whatever is arround it in the caller function.

    Now, the fix is to use the already existing CMSIS functions __disable_irq() and __enable_irq()
    instead of duplicating the inline assembly. The CMSIS functions DO contain the `: \"memory\" `
    statements that will instruct the compiler it cannot do assumptions about the memory after
    the inline assembly (aka, instruction barrier). "
    error: pathspec 'i does not contain the trailing  that acts
    like an implicit instruction barrier, this allows the compiler to reorder the instructions
    that disable the interrupts with whatever is arround it in the caller function.

    Now, the fix is to use the already existing CMSIS functions __disable_irq() and __enable_irq()
    instead of duplicating the inline assembly. The CMSIS functions DO contain the
    statements that will instruct the compiler it cannot do assumptions about the memory after
    the inline assembly (aka, instruction barrier). ' did not match any file(s) known to git