Add __wrap_ prefix to remquo and remquof calls
Linking with LTO enabled would otherwise result in an error with an
undefined reference to `__wrap_remquof' possibly because they are in
the same translation unit.